In [ ]:
import sys

# Python-an overview
Items of note
- Runtime Checked
- Indent based code blocks

## Math
- Also know as Arithmetic Operations
- Performed with arithmetic operators

> - Addition: **x + y**
> - Subtraction: **x - y**
> - Multiplication: **x * y**
> - Division: **x / y**
> - Modulus: **x % y**
> - Exponents: **x ** y**
> - Floor Division: **x // y**


## Numbers
### Integers

In [ ]:
sys.int_info

sys.int_info(bits_per_digit=30, sizeof_digit=4, default_max_str_digits=4300, str_digits_check_threshold=640)

In [ ]:
x = 5
print(x)

5


In [ ]:
x = sys.maxsize
y = -x
print("x:", x)
print("y:", y)

x: 9223372036854775807
y: -9223372036854775807


### Floats

In [ ]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [ ]:
import math

In [ ]:
x = 3.14159365
x

3.14159365

## Arrays
**Documentation:** https://docs.python.org/3/tutorial/datastructures.html \
In python arrays are called lists.

**Properties**:
> - Ordered
> - Mutable
> - Type Flexible
> - Allow Duplicates

In [ ]:
of_ints = [5, 6, 1 , 20, 64, 33, 85, 22, 27, 3]
print(of_ints)

[5, 6, 1, 20, 64, 33, 85, 22, 27, 3]


In [ ]:
of_strings = ['hello world', 'this is a sentence.', 'this is how a lot of data can be formatted']
print(of_strings)

['hello world', 'this is a sentence.', 'this is how a lot of data can be formatted']


In [ ]:
multi_ray = [5, 'a', 'you can have multiple types too', (4, 'four')]
print(multi_ray)

[5, 'a', 'you can have multiple types too', (4, 'four')]


In [ ]:
array_dim = [of_ints, of_strings, multi_ray]
print(array_dim)

[[5, 6, 1, 20, 64, 33, 85, 22, 27, 3], ['hello world', 'this is a sentence.', 'this is how a lot of data can be formatted'], [5, 'a', 'you can have multiple types too', (4, 'four')]]


#### Size and Indexing

In [ ]:
print(of_ints)
print("Length: ", len(of_ints)  )

[5, 6, 1, 20, 64, 33, 85, 22, 27, 3]
Length:  10


In [ ]:
of_ints[-2]


27

#### Slicing
Notation:  array[lower_bound : upper_bound : step]

In [ ]:
of_ints

[5, 6, 1, 20, 64, 33, 85, 22, 27, 3]

In [ ]:
print(of_ints[:7:-1])
print(of_ints[:7])
print(of_ints[3:])

[3, 27]
[5, 6, 1, 20, 64, 33, 85]
[20, 64, 33, 85, 22, 27, 3]


#### Searching

In [ ]:
print( 3 in of_ints)
print(44 in of_ints)

True
False


In [ ]:
of_strings

['hello world',
 'this is a sentence.',
 'this is how a lot of data can be formatted']

In [ ]:
print('hello world' in of_strings)
print('Hello World' in of_strings)

True
False


In [ ]:
print(of_strings in array_dim)

True


#### Changing arrays

In [ ]:
ray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
print(ray)
print(ray.index(5))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
4


In [ ]:
ray.remove(4)
print(ray)

[1, 2, 3, 5, 6, 7, 8, 9, 10]


In [ ]:
ray.append(4)
print(ray)

[1, 2, 3, 5, 6, 7, 8, 9, 10, 4]


In [ ]:
ray.pop(-1)

4

In [ ]:
ray.insert(3, 4)
print(ray)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
del ray[3]
ray

[1, 2, 3, 5, 6, 7, 8, 9, 10]

In [ ]:
ray.insert(3,4)
ray

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
ray[3]=77
ray

[1, 2, 3, 77, 5, 6, 7, 8, 9, 10]

In [ ]:
ray=[1,2,3,4,5]

In [ ]:
ray = ray*2
print(ray)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


## Text

> ### Characters
> - Technially Python does not have an explicit type char
> - Are numbers
> -Unicode character encodings

> ### Strings
> - Are an array of characters
> - Can use **either** " " or ' '
> - Formatted strings
> - Multiline Strings

In [ ]:
x = "Hello World!"
y = 'Hello World!'
print(x)
print(y)
print(x[4]) # is a character in other languages

Hello World!
Hello World!
o


In [ ]:
requests = 5
print(f"The user requested this {requests} many times\n")

The user requested this 5 many times



In [ ]:
block_quote = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Urna condimentum mattis pellentesque id nibh tortor.
Tortor consequat id porta nibh venenatis cras sed felis eget.
Dictum non consectetur a erat nam at. """

print(block_quote)

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Urna condimentum mattis pellentesque id nibh tortor.
Tortor consequat id porta nibh venenatis cras sed felis eget.
Dictum non consectetur a erat nam at. 


#### Searching

In [ ]:
print('world' in x)
print('World' in x)

False
True


#### Processing

In [ ]:
bq_stripped = block_quote.strip()
print(bq_stripped, "\n\n")

bq_rem = block_quote.replace(" ", "")
print(bq_rem, "\n\n")

bq_split = block_quote.split(" ")
print(bq_split)

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
Urna condimentum mattis pellentesque id nibh tortor.
Tortor consequat id porta nibh venenatis cras sed felis eget.
Dictum non consectetur a erat nam at. 


Loremipsumdolorsitamet,consecteturadipiscingelit,seddoeiusmodtemporincididuntutlaboreetdoloremagnaaliqua.
Urnacondimentummattispellentesqueidnibhtortor.
Tortorconsequatidportanibhvenenatiscrassedfeliseget.
Dictumnonconsecteturaeratnamat. 


['Lorem', 'ipsum', 'dolor', 'sit', 'amet,', 'consectetur', 'adipiscing', 'elit,', 'sed', 'do', 'eiusmod', 'tempor', 'incididunt', 'ut', 'labore', 'et', 'dolore', 'magna', 'aliqua.\nUrna', 'condimentum', 'mattis', 'pellentesque', 'id', 'nibh', 'tortor.\nTortor', 'consequat', 'id', 'porta', 'nibh', 'venenatis', 'cras', 'sed', 'felis', 'eget.\nDictum', 'non', 'consectetur', 'a', 'erat', 'nam', 'at.', '']


#### Concatenating


In [ ]:
x = 'Tortor consequat id porta nibh venenatis cras sed felis eget. '
y = "Dictum non consectetur a erat nam at."

z = x+y
print(z)
print("\n", x, "\n", y)

Tortor consequat id porta nibh venenatis cras sed felis eget. Dictum non consectetur a erat nam at.

 Tortor consequat id porta nibh venenatis cras sed felis eget.  
 Dictum non consectetur a erat nam at.


## Tuples
- Ordered
- Immutable
- Type Flexible
- Allow Duplicates

In [ ]:
tup = ('red', 'pink', 'blue', 'yellow', 'yellow')
print(tup)
x = tup[0]

('red', 'pink', 'blue', 'yellow', 'yellow')


#### Packing and Unpacking

In [ ]:
names = ( "Astarion", "Gale", "Lae'zel", "Wyll")
(c1, c2, c3, c4) = names

print(c1)
print(c2)
print(c3)
print(c4)


Astarion
Gale
Lae'zel
Wyll


In [ ]:
names = ( "Astarion", "Gale", "Lae'zel", "Wyll")
v1, v2, _, _ = names

print(v1)
print(v2)


Astarion
Gale


## Dictionaries
- Maps Key-Value pairs
- Visualize as a table
- Type flexible
- Mutable
- No duplicate keys allowed

In [ ]:
dict = {
    "RSVP" : 'Répondez s’il vous plait',
    'ASAP' : 'as soon as possible',
    "BBEG" : 'big bad evil guy',
    "SMH" : 'shaking my head',
    'AWOL' : 'absent without leave',
    'UFO' : 'unidentified flying object',
    "SCUBA" : "Self-contained underwater breathing apparatus"
}

In [ ]:
print(dict)

{'RSVP': 'Répondez s’il vous plait', 'ASAP': 'as soon as possible', 'BBEG': 'big bad evil guy', 'SMH': 'shaking my head', 'AWOL': 'absent without leave', 'UFO': 'unidentified flying object', 'SCUBA': 'Self-contained underwater breathing apparatus'}


In [ ]:
k=dict.keys()
v = dict.values()
print(k)
print(v)

dict_keys(['RSVP', 'ASAP', 'BBEG', 'SMH', 'AWOL', 'UFO', 'SCUBA'])
dict_values(['Répondez s’il vous plait', 'as soon as possible', 'big bad evil guy', 'shaking my head', 'absent without leave', 'unidentified flying object', 'Self-contained underwater breathing apparatus'])


#### Changing

In [ ]:
dict["CAD"] = "comupter aided design"
print(k)
print(v)
print(dict)

dict_keys(['RSVP', 'ASAP', 'BBEG', 'SMH', 'AWOL', 'UFO', 'SCUBA', 'CAD'])
dict_values(['Répondez s’il vous plait', 'as soon as possible', 'big bad evil guy', 'shaking my head', 'absent without leave', 'unidentified flying object', 'Self-contained underwater breathing apparatus', 'comupter aided design'])
{'RSVP': 'Répondez s’il vous plait', 'ASAP': 'as soon as possible', 'BBEG': 'big bad evil guy', 'SMH': 'shaking my head', 'AWOL': 'absent without leave', 'UFO': 'unidentified flying object', 'SCUBA': 'Self-contained underwater breathing apparatus', 'CAD': 'comupter aided design'}


In [ ]:
dict["SMH"] = "shrimp must have"
print(dict["SMH"])

shrimp must have


In [ ]:
dict.pop("SMH")
print(dict)

{'RSVP': 'Répondez s’il vous plait', 'ASAP': 'as soon as possible', 'BBEG': 'big bad evil guy', 'AWOL': 'absent without leave', 'UFO': 'unidentified flying object', 'SCUBA': 'Self-contained underwater breathing apparatus', 'CAD': 'comupter aided design'}


## Booleans
> Only two choices: True or False\
> If you are doing discrete math you are using booleans

In [ ]:
x= True
y=False

In [ ]:
True == 1

True

#### Logical Operators

In [ ]:
a = x or y
b = x and y
c = not x

print(a, b, c)

True False False


In [ ]:
y or not x and y

False

In [ ]:
y or not (x and y)

True

#### Comparison Operators
> - **==**
> - **!=**
> - **>**
> - **<**
> - **>=**
> - **<=**

#### Identity Operators
Identity operators test whether the things being compared are the same object
> - is
> - is not

In [ ]:
ray1 = ["one", 4, "two"]
ray2 = ray1.copy()
ray3 = ray1

print(ray1)
print(ray2)
print(ray3)

['one', 4, 'two']
['one', 4, 'two']
['one', 4, 'two']


In [ ]:
ray1 is ray3

True

In [ ]:
ray1 is ray2

False

#### Membership Operators

In [ ]:
"one" in ray1

True

In [ ]:
5 in ray1

False

#### Type Identification and Manipulation

## Loops
> - ### For
> - ### While

In [ ]:
for i in range(0,5):
  print(i)


0
1
2
3
4


In [ ]:
for x in of_ints:
    print(x)

5
6
1
20
64
33
85
22
27
3


In [ ]:
for key in dict:
    print(key + ": "+ dict[key])

RSVP: Répondez s’il vous plait
ASAP: as soon as possible
BBEG: big bad evil guy
AWOL: absent without leave
UFO: unidentified flying object
SCUBA: Self-contained underwater breathing apparatus
CAD: comupter aided design


In [ ]:
i=0;
while(i<5):
  print(of_ints[i]);
  i+=1;

5
6
1
20
64


## Functions

In [ ]:
def randfunction(dictionary, entry, x, y):
  """ RandFunction: adds a key-value pair into a dictionary
  parameters: dictionary-dictionary containing acronyms
  entry-new entry into the dictionary
  x: integer for condition
  y: integer for condition"""
  if x > y:
    dictionary[entry[0]]= entry[1]

  return "completed"

In [ ]:
x = randfunction(dict, ("STEM", "science, technology, engineering, and math"), 2, 5)

In [ ]:
dict

{'RSVP': 'Répondez s’il vous plait',
 'ASAP': 'as soon as possible',
 'BBEG': 'big bad evil guy',
 'AWOL': 'absent without leave',
 'UFO': 'unidentified flying object',
 'SCUBA': 'Self-contained underwater breathing apparatus',
 'CAD': 'comupter aided design'}

In [ ]:
print(x)

completed


### Variable Scope
> Variables declared outside a function are always global\
> Variables declared inside a function can be denoted as global with the global keyword\
> If you are changing a global variable inside a function invoke global

In [ ]:
x=2
def randfunction2(entry, x, y):
    print(x)
    global dictionary
    dictionary = {}
    if x > y:
        dictionary[entry[0]]= entry[1]

In [ ]:
randfunction2(("EDA", "exploratory data analysis"), 7,5)

7


In [ ]:
dictionary

{'EDA': 'exploratory data analysis'}

# Numpy
References: https://numpy.org/devdocs/user/absolute_beginners.html

In [ ]:
import numpy as np

In [ ]:
np_array = np.random.randint(100, size=(4,3))

In [ ]:
type(np_array)

numpy.ndarray

In [ ]:
np_array

array([[98, 94, 55],
       [42, 11, 64],
       [65, 29, 29],
       [ 8, 86, 89]])

In [ ]:
np_array.size

12

In [ ]:
np_array.shape

(4, 3)

So what's the difference between a python arraylist and a numpy array?


*   All elements must be the same type
*   Total size of the array is immutable
* Each row must have the same number of colunmns
* Slicing does not return a copy but returns a view which is linked to the original object in memory



In [ ]:
ray = [1,2,3,4,5,6,7,8,9,10]
nray = np.array(ray)

In [ ]:
nray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

The standard numpy array generators

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(4,10,2)

array([4, 6, 8])

In [ ]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[5, 6, 7, 8], [1, 2,3, 4]])

In [ ]:
c = np.concatenate((a,b), axis = 0)

In [ ]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
z = np.concatenate((y,x), axis=0)

In [ ]:
z

array([[5, 6],
       [1, 2],
       [3, 4]])

In [ ]:
new_ray = nray*z

ValueError: operands could not be broadcast together with shapes (10,) (3,2) 

Reshaping arrays

In [ ]:
np_array

array([[98, 94, 55],
       [42, 11, 64],
       [65, 29, 29],
       [ 8, 86, 89]])

In [ ]:
np_array.shape

(4, 3)

In [ ]:
np_array = np_array.reshape((2,6))

In [ ]:
np_array

array([[98, 94, 55, 42, 11, 64],
       [65, 29, 29,  8, 86, 89]])

In [ ]:
np_array.T

array([[98, 65],
       [94, 29],
       [55, 29],
       [42,  8],
       [11, 86],
       [64, 89]])

In [ ]:
np_array.flatten()

In [ ]:
np_array.reshape((1, 12))

# Packages


*   Scipy: https://pypi.org/project/scipy/
    

> SciPy (pronounced “Sigh Pie”) is an open-source software for mathematics, science, and engineering. It includes modules for statistics, optimization, integration, linear algebra, Fourier transforms, signal and image processing, ODE solvers, and more.


*   Pingouin: https://pingouin-stats.org/build/html/index.html


> Pingouin is an open-source statistical package written in Python 3 and based mostly on Pandas and NumPy. Some of its main features include: ANOVAs, Pairwise post-hocs tests and pairwise correlations, Robust, partial, distance and repeated measures correlations, Linear/logistic regression and mediation analysis, Bayes Factors, Multivariate tests, Reliability and consistency, Effect sizes and power analysis, Parametric/bootstrapped confidence intervals around an effect size or a correlation coefficient, Circular statistics, Chi-squared tests, Plotting: Bland-Altman plot, Q-Q plot, paired plot, robust correlation…


* Sklearn: https://scikit-learn.org/stable/


> Machine learning library with classification, regression, clustering algorithms as well as dimensionality reduction, model selection, and preprocessing.

*Open3D: https://www.open3d.org/

> Open3D is a open-source libray that supports 3D data. It features 3D data structures, 3D data processign algorithms, scene reconstruction, surface alignment, 3D visualizations, machine learning support, and GPU acceleation for core 3D operations.
